export { default as NavBar } from "./NavBar/NavBar"
export { default as Home } from "./Home/Home"
export { default as Footer } from "./Footer/Footer"
export { default as Hero } from "./Hero/Hero"
export { default as Information } from "./Informational/Information"
